---
- name: AWS SSM assume
  hosts: ssm
  gather_facts: false
  tasks:

    # This is assuming a role SSMSeanTesting configured under IAM
    - name: SSMrole
      amazon.aws.sts_assume_role:
        role_arn: arn:aws:iam::962147768365:role/SSMSeanTesting
        role_session_name: "seantestrole"
      register: assumed_role
      delegate_to: localhost
      run_once: true

    - name: Print out assumed_role info
      ansible.builtin.debug:
        var: assumed_role

     # The SSMSeanTestingRole has 2 acces permissions and works
     # AmazonSSMFullAccess
     # AmazonS3FullAccess
    - name: Do file module via SSM
      vars:
        ansible_aws_ssm_access_key_id: "{{ assumed_role.sts_creds.access_key }}"
        ansible_aws_ssm_secret_access_key: "{{ assumed_role.sts_creds.secret_key }}"
        ansible_aws_ssm_session_token: "{{ assumed_role.sts_creds.session_token }}"
        ansible_connection: "community.aws.aws_ssm"
        ansible_aws_ssm_region: "us-east-1"
        ansible_aws_ssm_bucket_name: "ssmtestingoctober"
        ansible_aws_ssm_instance_id: i-09793f817c1a29bf4
        ansible_user: ssm-user
      ansible.builtin.file:
        path: blah.txt
        state: touch
      register: output

    - name: Print out output
      ansible.builtin.debug:
        var: output

   # This won't work b/c the assume role can only do S3 and SSM
    - name: Tag ec2
      amazon.aws.ec2_tag:
        aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
        aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
        security_token: "{{ assumed_role.sts_creds.session_token }}"
        resource: vpc-0ae1d7baeaa323b44
        state: present
        tags:
          Name: craigcraig-f5-vpc
      delegate_to: localhost
      run_once: true
