---
- name: This Ansible Playbook will stop instances instances
  hosts: localhost
  gather_facts: false
  vars:
    ec2_region: "{{ your_region | default('us-east-1') }}"
  tasks:
    - name: Stop every un-tagged running instance in a region.
      amazon.aws.ec2_instance:
        region: "{{ ec2_region }}"
        state: stopped
        instance_ids: "{{ identified_instances }}"
      when: identified_instances | length  > 0
